### ISSUE TITLE
pg. 49, Implementing ContentResult

### ISSUE THREAD

**Issue by fivefishstudios** [csharpschool/AspNetCoreVideo#1]
I'm wondering why this is not working. It looks exactly like in the book and also your github example. I'm using Microsoft.AspNetCore.Mvc;

`
using Microsoft.AspNetCore.Mvc;
namespace ASPNetCoreVideo.Controllers
{
    // attribute routing for MVC
    [Route("company/[controller]/[action]")]
    public class EmployeeController : Controller    // error here.... 
  {     
      public ContentResult Name( )        
      {
        return Content("John Doe");      // error here.... 
      }

      public string Country( )
      {
        return "United States";
      }

      public string JobTitle( )
      {
        return "Web Developer";
      }

      public string Index( )
      {
        return "Hello from EmployeeController() class";
      }      
    }
}
`

Error message is

Error | CS0246 | The type or namespace name 'Controller' could not be found (are you missing a using directive or an assembly reference?) 

Error | CS0103 | The name 'Content' does not exist in the current context    

-- Now, I can get rid of the errors by using System.Web.Mvc but the program doesn't work and the url /company/employee/name does not work and give the correct result. (just an empty page)

/company/employee/country also doesn't work. 
but /employee/country works.  

So it seems the [Route] is being ignored if I use using System.Web.Mvc 
But that's the only way I can get rid of the error messages.

**Comment by fivefishstudios** [comment]
Jonas, I got example on page 49  working by changing

public class EmployeeController : _Controller_
into
public class EmployeeController : **ControllerBase**

**Comment by csharpschool** [comment]
Sorry for not replying to your issue.

Glad you found a solution. It could be that Microsoft has made a small change in the framework recently.
Please let me know if you find anything else or need help.

In the future, if you run into problem and want a faster response please send me an email at csharpschoolonline@gmail.com. You can also find the email address in the book.
