### ISSUE TITLE
Wrong text no page 15/16 (paperback)

### ISSUE THREAD

**Issue by csharpschool** [csharpschool/AspNetCoreVideo#4]
The text:

> The Configure method is where you set up the application’s inversion of control container, which will be covered more in the second part of this book.
> The second method in the Startup class is ConfigureServices, which is used to configure the application services.

Should be:

> In the Configure method, you setup the HTTP request pipeline (the middleware) that is called when the application starts. In the second part of this book, you will add an object-to-object mapper called AutoMapper to this method. AutoMapper transforms objects from one type to another.
> The ConfigureServices method is where you set up the services, such as MVC. You can also register your own services and make them ready for DI, for instance the services that you implement using the IMessageService interface at the beginning of the book.

**Comment by howardhwa** [comment]
Title still has typo~

**Comment by csharpschool** [comment]
Sorry for the late replay.
Yes it still has the typos specified here, I haven't had the time to format and upload a new version of the book. I will post a new Issue here when the book has been updated.
